app/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.ext.automap import automap_base
from flask_login import UserMixin
from datetime import datetime

# Create a database object
db = SQLAlchemy()

# Init db and return list of class tables
def init_db(app):
    db.init_app(app)
    # Reflect the existing database schema
    Base = automap_base()
    with app.app_context():
        Base.prepare(db.engine, reflect=True)

        # Access the reflected tables
        User = Base.classes.User 
        Account_Details = Base.classes.Account_Details
        Address = Base.classes.Address
        Card = Base.classes.Card
        Cart = Base.classes.Cart
        Category = Base.classes.Category
        Order_Item = Base.classes.Order_Item
        Preferences = Base.classes.Preferences
        Product = Base.classes.Product
        Report = Base.classes.Report
        Shipment = Base.classes.Shipment
        Transaction = Base.classes.Transaction
 # Return the reflected classes for use elsewhere in the application
    return {
        'User': User,
        'Account_Details': Account_Details,
        'Address': Address,
        'Card': Card,
        'Cart': Cart,
        'Category': Category,
        'Order_Item': Order_Item,
        'Preferences': Preferences,
        'Product': Product,
        'Report': Report,
        'Shipment': Shipment,
        'Transaction': Transaction
    }


# UserMixin is used directly with the reflected User class
class User(UserMixin, db.Model):
    __tablename__ = 'User'  # Set the tablename

    # Define the columns of the User table
    User_ID = db.Column(db.Integer, primary_key=True)
    Username = db.Column(db.String(45), unique=True)
    Password_hash = db.Column(db.String(260))
    UserType = db.Column(db.String(20))
    RegistrationDate = db.Column(db.DateTime)  
    LastLogin = db.Column(db.DateTime)         
    UserStatus = db.Column(db.String(45))

    def get_id(self):
        return str(self.User_ID) # convert ID to string if it is not already a string

app/__init__.py
from flask import Flask, Blueprint
from flask import render_template, url_for, request, make_response, session 
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import app_config
from app.models import init_db

# Create Flask application instance
app = Flask(__name__)

# Load configuration from config module
app.config.from_object('config.app_config')

# Initialize db and return list of class tables
tables = init_db(app)

# Login manager
login_manager = LoginManager()
login_manager.login_view = 'auth_blueprint.login'
login_manager.init_app(app)

from .models import User 

@login_manager.user_loader
def load_user(User_ID):
    # the user_id is just the PK of our user
    return User.query.get(int(User_ID))



# Import blueprints
from app.admin import admin_blueprint 
from app.general import general_blueprint
from app.auth import auth_blueprint
from app.cart import cart_blueprint
from app.shop import shop_blueprint

# Register blueprints
app.register_blueprint(admin_blueprint, url_prefix='/')
app.register_blueprint(general_blueprint, url_prefix='/')
app.register_blueprint(auth_blueprint, url_prefix='/')
app.register_blueprint(cart_blueprint, url_prefix='/')
app.register_blueprint(shop_blueprint, url_prefix='/')

app/admin/__init__.py
from flask import Blueprint
from flask import render_template, url_for

admin_blueprint = Blueprint('admin_blueprint', 
                            __name__,
                            template_folder='templates',
                            static_folder='static',
                            static_url_path='assests')

from . import views

app/admin/views.py
from flask import render_template, url_for, redirect
from . import admin_blueprint
from flask import current_app
from app import tables
from app.models import  db 

@admin_blueprint.route('/admin/')
def admin_page():
    user = db.session.query(tables['User']).first()
    #return f"This page {user.Username}"
    return render_template("/dashboard.html")

app/cart/__init__.py
from flask import Blueprint

cart_blueprint = Blueprint('cart_blueprint', 
                           __name__,
                           template_folder='templates/cart',
                           static_folder='static',
                           static_url_path='assets')

from . import views 

app/cart/views.py
from flask import render_template
from . import cart_blueprint

@cart_blueprint.route('/cart/')
def cart():
    return render_template('test.html')

app/general/__init__.py
from flask import Blueprint,render_template
from flask_login import current_user, login_required

general_blueprint = Blueprint('general_blueprint', __name__,
                                template_folder='templates',
                               static_folder='static',
                               static_url_path='assests')

@general_blueprint.route('/')
def index():
    return render_template("index.html")

@general_blueprint.route('/profile')
@login_required
def profile():
    return render_template("profile.html", name=current_user.Username)

app/shop/__init__.py
from flask import Blueprint

shop_blueprint = Blueprint('shop_blueprint', 
                           __name__,
                           template_folder='templates/shop',
                           static_folder='static',
                           static_url_path='assests')

from . import views 

app/shop/views.py
from flask import render_template
from . import shop_blueprint

@shop_blueprint.route('/shop')
def shop():
    return render_template('cart.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TinkerBuy E-Commerce</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')  }}">
    <link rel="stylesheet" href="">
</head>
<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('general_blueprint.index') }}" class="navbar-item fa fa-home">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('general_blueprint.index') }}" class="navbar-item fa">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth_blueprint.login') }}" class="navbar-item fa">
                                Login
                            </a>
                            <a href="{{ url_for('auth_blueprint.signup') }}" class="navbar-item fa">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth_blueprint.logout') }}" class="navbar-item fa">
                                Logout
                            </a>
                            <a href="{{ url_for('cart_blueprint.cart') }}" class="navbar-item fa fa-shopping-cart">
                                Cart
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>

    <footer>
        <p>© 2024 TinkerBuy. All rights reserved.</p>
    </footer>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
   <header>
        <h1>Welcome to TinkerBuy</h1>
        <p>Your one-stop shop for all things amazing!</p>
    </header>
   <nav>
        <ul>
            <li><button onclick="location.href='base.html'"><i class="fa fa-home"></i>Home</button></li>
            <li><button onclick="location.href='../auth/templates/auth/login.html'"><i class="fa fa-shopping-cart"></i>Products</button></li>
            <li><button onclick="location.href='../admin/templates/admin/product_management.html'"><i class="fa fa-key"></i>Admin</button></li>
            <li><a href="#"><i class="fa fa-phone-alt"></i>Contact</a></li>
        </ul>
    </nav>

       <div>
        <section>
            <h2>Featured Products</h2>
            <div class="product-container">
                <div class="image-container">
                    <img src="ComputerChip.jpg" alt="Motherboard" class="product-image" />
                    <p class="image-caption">Motherboard</p>
                </div>
                <div class="image-container">
                    <img src="ComputerChip2.jpg" alt="ComputerChip" class="product-image" />
                    <p class="image-caption">3 Computer Chips</p>
                </div>
                <div class="image-container">
                    <img src="KeyboardMouseHeadphones.jpg" alt="Computer accessories" class="product-image" />
                    <p class="image-caption">Computer Accessories</p>
                </div>
            </div>
        </section>
        </div>

{% endblock %}